/* eslint-disable */
/** Auto-generated by scripts/build_catalog.py — do not edit by hand. */

export const UNIT_ROWS = [
  {
    "code": "HS1-01",
    "label": "다항식",
    "school": "고등학교",
    "grade": "1학년"
  },
  {
    "code": "HS1-02",
    "label": "방정식과 부등식",
    "school": "고등학교",
    "grade": "1학년"
  },
  {
    "code": "HS1-03",
    "label": "경우의 수",
    "school": "고등학교",
    "grade": "1학년"
  },
  {
    "code": "HS1-04",
    "label": "도형의 방정식",
    "school": "고등학교",
    "grade": "1학년"
  },
  {
    "code": "HS1-05",
    "label": "집합과 명제",
    "school": "고등학교",
    "grade": "1학년"
  },
  {
    "code": "HS1-06",
    "label": "함수",
    "school": "고등학교",
    "grade": "1학년"
  },
  {
    "code": "MS1-01",
    "label": "수와 연산",
    "school": "중학교",
    "grade": "1학년"
  },
  {
    "code": "MS1-02",
    "label": "문자와 식·방정식",
    "school": "중학교",
    "grade": "1학년"
  },
  {
    "code": "MS1-03",
    "label": "좌표와 그래프",
    "school": "중학교",
    "grade": "1학년"
  },
  {
    "code": "MS1-04",
    "label": "기본 도형",
    "school": "중학교",
    "grade": "1학년"
  },
  {
    "code": "MS1-05",
    "label": "원과 입체",
    "school": "중학교",
    "grade": "1학년"
  },
  {
    "code": "MS1-06",
    "label": "자료의 정리",
    "school": "중학교",
    "grade": "1학년"
  },
  {
    "code": "MS2-01",
    "label": "유리수와 순환소수",
    "school": "중학교",
    "grade": "2학년"
  },
  {
    "code": "MS2-02",
    "label": "식의 계산",
    "school": "중학교",
    "grade": "2학년"
  },
  {
    "code": "MS2-03",
    "label": "부등식과 연립방정식",
    "school": "중학교",
    "grade": "2학년"
  },
  {
    "code": "MS2-04",
    "label": "일차함수",
    "school": "중학교",
    "grade": "2학년"
  },
  {
    "code": "MS2-05",
    "label": "삼각형과 사각형",
    "school": "중학교",
    "grade": "2학년"
  },
  {
    "code": "MS2-06",
    "label": "닮음",
    "school": "중학교",
    "grade": "2학년"
  },
  {
    "code": "MS2-07",
    "label": "피타고라스 정리",
    "school": "중학교",
    "grade": "2학년"
  },
  {
    "code": "MS2-08",
    "label": "확률",
    "school": "중학교",
    "grade": "2학년"
  },
  {
    "code": "MS3-01",
    "label": "제곱근과 실수",
    "school": "중학교",
    "grade": "3학년"
  },
  {
    "code": "MS3-02",
    "label": "다항식의 곱셈과 인수분해",
    "school": "중학교",
    "grade": "3학년"
  },
  {
    "code": "MS3-03",
    "label": "이차방정식",
    "school": "중학교",
    "grade": "3학년"
  },
  {
    "code": "MS3-04",
    "label": "이차함수",
    "school": "중학교",
    "grade": "3학년"
  },
  {
    "code": "MS3-05",
    "label": "피타고라스 정리",
    "school": "중학교",
    "grade": "3학년"
  },
  {
    "code": "MS3-06",
    "label": "삼각비",
    "school": "중학교",
    "grade": "3학년"
  },
  {
    "code": "MS3-07",
    "label": "원의 성질",
    "school": "중학교",
    "grade": "3학년"
  },
  {
    "code": "MS3-08",
    "label": "대푯값",
    "school": "중학교",
    "grade": "3학년"
  },
  {
    "code": "MS3-09",
    "label": "산포도",
    "school": "중학교",
    "grade": "3학년"
  },
  {
    "code": "MS3-10",
    "label": "산점도와 상관관계",
    "school": "중학교",
    "grade": "3학년"
  }
] as const;

export const TOPIC_ROWS = [
  {
    "code": "10공수1-01-01",
    "label": "다항식의 사칙연산",
    "unitCode": "HS1-01"
  },
  {
    "code": "10공수1-01-02",
    "label": "항등식과 나머지정리",
    "unitCode": "HS1-01"
  },
  {
    "code": "10공수1-01-03",
    "label": "다항식의 인수분해",
    "unitCode": "HS1-01"
  },
  {
    "code": "10공수1-02-01",
    "label": "복소수",
    "unitCode": "HS1-02"
  },
  {
    "code": "10공수1-02-02",
    "label": "이차방정식의 판별식",
    "unitCode": "HS1-02"
  },
  {
    "code": "10공수1-02-03",
    "label": "근과 계수의 관계",
    "unitCode": "HS1-02"
  },
  {
    "code": "10공수1-02-04",
    "label": "이차방정식과 이차함수",
    "unitCode": "HS1-02"
  },
  {
    "code": "10공수1-02-05",
    "label": "이차함수와 직선의 위치 관계",
    "unitCode": "HS1-02"
  },
  {
    "code": "10공수1-02-06",
    "label": "이차함수의 최대·최소",
    "unitCode": "HS1-02"
  },
  {
    "code": "10공수1-02-07",
    "label": "삼차·사차방정식",
    "unitCode": "HS1-02"
  },
  {
    "code": "10공수1-02-08",
    "label": "연립이차방정식",
    "unitCode": "HS1-02"
  },
  {
    "code": "10공수1-02-09",
    "label": "연립일차부등식",
    "unitCode": "HS1-02"
  },
  {
    "code": "10공수1-02-10",
    "label": "절댓값 부등식",
    "unitCode": "HS1-02"
  },
  {
    "code": "10공수1-02-11",
    "label": "이차부등식",
    "unitCode": "HS1-02"
  },
  {
    "code": "10공수1-03-01",
    "label": "합의 법칙과 곱의 법칙",
    "unitCode": "HS1-03"
  },
  {
    "code": "10공수1-03-02",
    "label": "순열",
    "unitCode": "HS1-03"
  },
  {
    "code": "10공수1-03-03",
    "label": "조합",
    "unitCode": "HS1-03"
  },
  {
    "code": "10공수2-01-01",
    "label": "선분의 내분",
    "unitCode": "HS1-04"
  },
  {
    "code": "10공수2-01-02",
    "label": "두 직선의 평행·수직",
    "unitCode": "HS1-04"
  },
  {
    "code": "10공수2-01-03",
    "label": "점과 직선 사이의 거리",
    "unitCode": "HS1-04"
  },
  {
    "code": "10공수2-01-04",
    "label": "원의 방정식",
    "unitCode": "HS1-04"
  },
  {
    "code": "10공수2-01-05",
    "label": "원과 직선의 위치 관계",
    "unitCode": "HS1-04"
  },
  {
    "code": "10공수2-01-06",
    "label": "평행이동",
    "unitCode": "HS1-04"
  },
  {
    "code": "10공수2-01-07",
    "label": "대칭이동",
    "unitCode": "HS1-04"
  },
  {
    "code": "10공수2-02-01",
    "label": "집합의 개념",
    "unitCode": "HS1-05"
  },
  {
    "code": "10공수2-02-02",
    "label": "집합의 포함관계",
    "unitCode": "HS1-05"
  },
  {
    "code": "10공수2-02-03",
    "label": "집합의 연산",
    "unitCode": "HS1-05"
  },
  {
    "code": "10공수2-02-04",
    "label": "명제와 조건",
    "unitCode": "HS1-05"
  },
  {
    "code": "10공수2-02-05",
    "label": "명제의 역과 대우",
    "unitCode": "HS1-05"
  },
  {
    "code": "10공수2-02-06",
    "label": "충분·필요조건",
    "unitCode": "HS1-05"
  },
  {
    "code": "10공수2-02-07",
    "label": "대우·귀류법",
    "unitCode": "HS1-05"
  },
  {
    "code": "10공수2-02-08",
    "label": "절대부등식",
    "unitCode": "HS1-05"
  },
  {
    "code": "10공수2-03-01",
    "label": "함수의 개념",
    "unitCode": "HS1-06"
  },
  {
    "code": "10공수2-03-02",
    "label": "합성함수",
    "unitCode": "HS1-06"
  },
  {
    "code": "10공수2-03-03",
    "label": "역함수",
    "unitCode": "HS1-06"
  },
  {
    "code": "10공수2-03-04",
    "label": "유리함수",
    "unitCode": "HS1-06"
  },
  {
    "code": "10공수2-03-05",
    "label": "무리함수",
    "unitCode": "HS1-06"
  },
  {
    "code": "9수01-01",
    "label": "소인수분해",
    "unitCode": "MS1-01"
  },
  {
    "code": "9수01-02",
    "label": "최대공약수와 최소공배수",
    "unitCode": "MS1-01"
  },
  {
    "code": "9수01-03",
    "label": "정수와 유리수",
    "unitCode": "MS1-01"
  },
  {
    "code": "9수01-04",
    "label": "정수·유리수의 대소",
    "unitCode": "MS1-01"
  },
  {
    "code": "9수01-05",
    "label": "정수·유리수의 사칙계산",
    "unitCode": "MS1-01"
  },
  {
    "code": "9수01-06",
    "label": "순환소수",
    "unitCode": "MS2-01"
  },
  {
    "code": "9수01-07",
    "label": "제곱근의 뜻과 성질",
    "unitCode": "MS3-01"
  },
  {
    "code": "9수01-08",
    "label": "무리수의 개념",
    "unitCode": "MS3-01"
  },
  {
    "code": "9수01-09",
    "label": "실수의 대소 관계",
    "unitCode": "MS3-01"
  },
  {
    "code": "9수01-10",
    "label": "근호를 포함한 식의 사칙계산",
    "unitCode": "MS3-01"
  },
  {
    "code": "9수02-01",
    "label": "문자를 사용한 식",
    "unitCode": "MS1-02"
  },
  {
    "code": "9수02-02",
    "label": "일차식의 덧셈과 뺄셈",
    "unitCode": "MS1-02"
  },
  {
    "code": "9수02-03",
    "label": "방정식과 등식의 성질",
    "unitCode": "MS1-02"
  },
  {
    "code": "9수02-04",
    "label": "일차방정식",
    "unitCode": "MS1-02"
  },
  {
    "code": "9수02-05",
    "label": "순서쌍과 좌표",
    "unitCode": "MS1-03"
  },
  {
    "code": "9수02-06",
    "label": "그래프의 해석",
    "unitCode": "MS1-03"
  },
  {
    "code": "9수02-07",
    "label": "정비례와 반비례",
    "unitCode": "MS1-03"
  },
  {
    "code": "9수02-08",
    "label": "지수법칙",
    "unitCode": "MS2-02"
  },
  {
    "code": "9수02-09",
    "label": "다항식의 덧셈과 뺄셈",
    "unitCode": "MS2-02"
  },
  {
    "code": "9수02-10",
    "label": "단항식과 다항식의 곱셈·나눗셈",
    "unitCode": "MS2-02"
  },
  {
    "code": "9수02-11",
    "label": "부등식의 성질",
    "unitCode": "MS2-03"
  },
  {
    "code": "9수02-12",
    "label": "일차부등식",
    "unitCode": "MS2-03"
  },
  {
    "code": "9수02-13",
    "label": "연립일차방정식",
    "unitCode": "MS2-03"
  },
  {
    "code": "9수02-14",
    "label": "함수의 개념",
    "unitCode": "MS2-04"
  },
  {
    "code": "9수02-15",
    "label": "일차함수의 개념",
    "unitCode": "MS2-04"
  },
  {
    "code": "9수02-16",
    "label": "일차함수의 그래프",
    "unitCode": "MS2-04"
  },
  {
    "code": "9수02-17",
    "label": "일차함수와 일차방정식",
    "unitCode": "MS2-04"
  },
  {
    "code": "9수02-18",
    "label": "두 일차함수와 연립방정식",
    "unitCode": "MS2-04"
  },
  {
    "code": "9수02-19",
    "label": "다항식의 곱셈과 인수분해",
    "unitCode": "MS3-02"
  },
  {
    "code": "9수02-20",
    "label": "이차방정식",
    "unitCode": "MS3-03"
  },
  {
    "code": "9수02-21",
    "label": "이차함수의 개념",
    "unitCode": "MS3-04"
  },
  {
    "code": "9수02-22",
    "label": "이차함수의 그래프와 성질",
    "unitCode": "MS3-04"
  },
  {
    "code": "9수03-01",
    "label": "점·선·면·각",
    "unitCode": "MS1-04"
  },
  {
    "code": "9수03-02",
    "label": "평행선의 성질",
    "unitCode": "MS1-04"
  },
  {
    "code": "9수03-03",
    "label": "삼각형의 작도",
    "unitCode": "MS1-04"
  },
  {
    "code": "9수03-04",
    "label": "삼각형의 합동",
    "unitCode": "MS1-04"
  },
  {
    "code": "9수03-05",
    "label": "다각형의 성질",
    "unitCode": "MS1-04"
  },
  {
    "code": "9수03-06",
    "label": "부채꼴",
    "unitCode": "MS1-05"
  },
  {
    "code": "9수03-07",
    "label": "다면체와 회전체",
    "unitCode": "MS1-05"
  },
  {
    "code": "9수03-08",
    "label": "입체도형의 겉넓이와 부피",
    "unitCode": "MS1-05"
  },
  {
    "code": "9수03-09",
    "label": "이등변삼각형",
    "unitCode": "MS2-05"
  },
  {
    "code": "9수03-10",
    "label": "삼각형의 외심과 내심",
    "unitCode": "MS2-05"
  },
  {
    "code": "9수03-11",
    "label": "사각형의 성질",
    "unitCode": "MS2-05"
  },
  {
    "code": "9수03-12",
    "label": "도형의 닮음",
    "unitCode": "MS2-06"
  },
  {
    "code": "9수03-13",
    "label": "삼각형의 닮음",
    "unitCode": "MS2-06"
  },
  {
    "code": "9수03-14",
    "label": "평행선 사이의 선분의 길이의 비",
    "unitCode": "MS2-06"
  },
  {
    "code": "9수03-15",
    "label": "피타고라스 정리",
    "unitCode": "MS2-07"
  },
  {
    "code": "9수03-16",
    "label": "삼각비의 뜻과 값",
    "unitCode": "MS3-06"
  },
  {
    "code": "9수03-17",
    "label": "삼각비의 활용",
    "unitCode": "MS3-06"
  },
  {
    "code": "9수03-18",
    "label": "원의 현·접선",
    "unitCode": "MS3-07"
  },
  {
    "code": "9수03-19",
    "label": "원주각",
    "unitCode": "MS3-07"
  },
  {
    "code": "9수04-01",
    "label": "대푯값(중앙값·최빈값)",
    "unitCode": "MS3-08"
  },
  {
    "code": "9수04-02",
    "label": "자료의 정리와 해석",
    "unitCode": "MS1-06"
  },
  {
    "code": "9수04-03",
    "label": "상대도수",
    "unitCode": "MS1-06"
  },
  {
    "code": "9수04-05",
    "label": "경우의 수",
    "unitCode": "MS2-08"
  },
  {
    "code": "9수04-06",
    "label": "확률",
    "unitCode": "MS2-08"
  },
  {
    "code": "9수04-07",
    "label": "분산과 표준편차",
    "unitCode": "MS3-09"
  },
  {
    "code": "9수04-09",
    "label": "산점도와 상관관계",
    "unitCode": "MS3-10"
  }
] as const;
